openapi: "3.0.3"
info:
  title: "Base API"
  description: "This is the API documentation for Base Framework, change this on main.go"
  version: "2.0.0"
servers:
  - url: "http://localhost:8100"
    description: "Base Framework API Server (http)"
  - url: "https://localhost:8100"
    description: "Base Framework API Server (https)"
# Full OpenAPI spec available in swagger.json
